# Generated by Django 4.1.13 on 2025-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developerfile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
