# Generated by Django 4.1.13 on 2025-04-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_developerfile_description_developerfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('param_type', models.CharField(max_length=50)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('default', models.CharField(blank=True, max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.developerfile')),
            ],
        ),
    ]
