# Generated by Django 4.1.13 on 2025-04-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_developerparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundxmlfile',
            name='linked_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_xmls', to='api.manuscriptfile'),
        ),
    ]
