# Generated by Django 4.1.13 on 2025-05-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_groundxmlfile_linked_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionrecord',
            name='model_used',
        ),
        migrations.RemoveField(
            model_name='extractionrecord',
            name='user_file',
        ),
        migrations.DeleteModel(
            name='TestData',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExtractionRecord',
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
