# Generated by Django 4.1.13 on 2025-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_developerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerparameter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
